spring.application.name=plate-info

# Server config
server.port=8081

# Consul Configuration
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

# Service Discovery and Health Check Configuration
spring.cloud.consul.discovery.instanceId=${spring.application.name}:${random.value}
spring.cloud.consul.discovery.serviceName=${spring.application.name}
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.healthCheckPath=/actuator/health
spring.cloud.consul.discovery.healthCheckInterval=15s
spring.cloud.consul.discovery.register=true

spring.cloud.consul.config.format=YAML
spring.cloud.consul.config.prefixes=config
spring.cloud.consul.config.default-context=application
spring.cloud.consul.config.profile-separator=,

spring.config.import=optional:consul:

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
