spring.application.name=plate-info

# Server config
server.port=8081

# Consul Configuration
spring.cloud.consul.discovery.hostname=localhost
spring.cloud.consul.discovery.prefer-ip-address=false

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.config.import=optional:consul:  # Allows configuration to be imported from Consul

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info
