spring.application.name=plate-info

# Server config
server.port=8081

# Consul Configuration
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.config.import=optional:consul:

# Service Discovery and Health Check Configuration
spring.cloud.consul.discovery.instanceId=${spring.application.name}:${random.value}
spring.cloud.consul.discovery.serviceName=${spring.application.name}
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.healthCheckPath=/actuator/health
spring.cloud.consul.discovery.healthCheckInterval=15s
spring.cloud.consul.discovery.register=true

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
